version: "3"

services:
  nuxt:
    build: .
    container_name: ia_front
    volumes:
      - ./libs:/usr/src/nuxt-app/libs
      - ./static:/usr/src/nuxt-app/static
      - ./pages:/usr/src/nuxt-app/pages
      - ./components:/usr/src/nuxt-app/components
    restart: always
    ports:
      - "6001:6001"
    expose:
      - "6001"
    command:
      "npm run dev"
    environment:
      VIRTUAL_HOST: ia.ifg.edu.br
      HTTP_PORT: 6001
      LETSENCRYPT_HOST: ia.ifg.edu.br
      LETSENCRYPT_EMAIL: "bcc@gmail.com"
      URL: "https://ia.ifg.edu.br/"

networks:
  default:
    external:
      name: nginx-proxy
